services:
  api:
    build: .
    container_name: peliculas-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - database
    # volumes:
    #   - .:/app

  database:
    image: postgres:15
    container_name: peliculas-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
    - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped